version: 2
jobs:
  test_toxicity_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/toxicity_model/requirements.txt
            PYTHONPATH=./packages/toxicity_model python3 ./download_data.py
            py.test -vv packages/toxicity_model/tests

workflows:
  version: 2
  test-all:
    jobs:
      - test_toxicity_model
