version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project

prepare_venv: &prepare_venv
  run:
    name: Create venv
    command: |
      python3 -m venv venv
      source venv/bin/activate
      pip install --upgrade pip

fetch_data: &fetch_data
  run:
    name: Set script permissions and fetch data
    command: |
      source venv/bin/activate
      PYTHONPATH=. python3 ./download_data.py

jobs:
  test_regression_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:-m
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r packages/toxicity_model/requirements.txt
      - *fetch_data

      - run:
          name: Run tests
          command: |
            . venv/bin/activate
            py.test -vv packages/toxicity_model/tests

  test_ml_api:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - py-deps-{{ checksum "packages/ml_api/requirements.txt" }}
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests
      - save_cache:
          key: py-deps-{{ checksum "packages/ml_api/requirements.txt" }}
          paths:
            - "/venv"

  upload_toxicity_model:
    <<: *defaults
    steps:
      - checkout
      - *prepare_venv
      - run:
          name: Install requirements
          command: |
            . venv/bin/activate
            pip install -r packages/toxicity_model/requirements.txt
      - *fetch_data
      - run:
          name: Publish model to Gemfury
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            ./scripts/publish_model.sh ./packages/toxicity_model/

workflows:
  version: 2
  test-all:
    jobs:
      - test_toxicity_model
      - test_ml_api
      - train_and_upload_toxicity_model:
          requires:
            - test_toxicity_model
            - test_ml_api
          filters:
            branches:
              only:
                - master
