version: 2
jobs:
  test_toxicity_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/toxicity_model/requirements.txt
            PYTHONPATH=. python3 ./download_data.py
            PYTHONPATH=./packages/toxicity_model py.test -vv packages/toxicity_model/tests

  test_ml_api:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Runnning tests
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install -r packages/ml_api/requirements.txt
            py.test -vv packages/ml_api/tests

  train_and_upload_toxicity_model:
    working_directory: ~/project
    docker:
      - image: circleci/python:3.7.2
    steps:
      - checkout
      - run:
          name: Setup env
          command: |
            virtualenv venv
            . venv/bin/activate
            pip install -r packages/toxicity_model/requirements.txt
      - run:
          name: Publish model
          command: |
            . venv/bin/activate
            chmod +x ./scripts/publish_model.sh
            PYTHONPATH=. python3 ./download_data.py
            PYTHONPATH=./packages/toxicity_model python3 packages/toxicity_model/toxicity_model/train_model.py
            ./scripts/publish_model.sh ./packages/toxicity_model/

workflows:
  version: 2
  test-all:
    jobs:
      - test_toxicity_model
      - test_ml_api
      - train_and_upload_toxicity_model
      - test_ml_api:
          requires:
            - train_and_upload_toxicity_model


